<?php
/**
 * @file
 * Code for the User feature.
 */

include_once 'wp_user.features.inc';


/**
 * Implements hook_form_alter()
 */
function wp_user_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id === 'user_register_form' || $form_id === 'user_profile_form') {
    $form['account']['name']['#required'] = FALSE;
    $form['account']['name']['#access'] = FALSE;

    array_unshift($form['#validate'], 'wp_user_user_form_validate');
  }
  elseif ($form_id === 'user_login') {
    $form['name']['#title'] = t("Mail");
    $form['name']['#description'] = t("Enter your mail address.");
  }
}

/**
 * Custom validate for user forms.
 */
function wp_user_user_form_validate(&$form, &$form_state) {
  $form_state['values']['name'] = $form_state['values']['mail'];
}
